#!/bin/bash

gcloud container clusters create vault \
  --enable-autorepair \
  --cluster-version 1.9.6-gke.1 \
  --machine-type n1-standard-2 \
  --num-nodes 2 \
  --zone us-west1-c

gcloud container clusters get-credentials vault

kubectl config rename-context gke_hightowerlabs_us-west1-c_vault vault
