apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    name: vault
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8200
      protocol: "TCP"
    - name: server
      port: 8201
      protocol: "TCP"
    - name: ui
      port: 443
      protocol: "TCP"
      targetPort: 8200
  selector:
    app: vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  vault.hcl: |
    disable_mlock = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_cert_file = "/etc/vault/tls/vault.pem"
      tls_client_ca_file = "/etc/vault/tls/ca.pem"
      tls_key_file = "/etc/vault/tls/vault-key.pem"
      tls_min_version = "tls12"
      tls_require_and_verify_client_cert = "true"
    }

    storage "gcs" {
      bucket = "vault-us-west1"
      ha_enabled = "true"
    }
    
    ui = true
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: "vault:0.10.0"
          args:
            - "server"
            - "-config=/etc/vault/config/vault.hcl"
          ports:
            - name: http
              containerPort: 8200
              protocol: "TCP"
            - name: server
              containerPort: 8201
              protocol: "TCP"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
            - name: vault-tls
              mountPath: /etc/vault/tls
      volumes:
        - name: vault-config
          configMap:
            name: vault
        - name: vault-tls
          secret:
            secretName: vault
