apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-0
  labels:
    app: vault
    instance: "0"
spec:
  selector:
    matchLabels:
      app: vault
      instance: "0"
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
        instance: "0"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - vault
              topologyKey: kubernetes.io/hostname
      containers:
        - name: vault
          image: "vault:0.10.0"
          env:
            - name: "VAULT_API_ADDR"
              valueFrom:
                configMapKeyRef:
                  name: vault-0
                  key: api-addr
            - name: "VAULT_CLUSTER_ADDR"
              value: "https://vault-0.default.svc.cluster.local:8201"
          args:
            - "server"
            - "-config=/etc/vault/config/vault.hcl"
          ports:
            - name: http
              containerPort: 8200
              protocol: "TCP"
            - name: server
              containerPort: 8201
              protocol: "TCP"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
            - name: vault-tls
              mountPath: /etc/vault/tls
      volumes:
        - name: vault-config
          configMap:
            name: vault
        - name: vault-tls
          secret:
            secretName: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-1
  labels:
    app: vault
    instance: "1"
spec:
  selector:
    matchLabels:
      app: vault
      instance: "1"
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
        instance: "1"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - vault
              topologyKey: kubernetes.io/hostname
      containers:
        - name: vault
          image: "vault:0.10.0"
          env:
            - name: "VAULT_API_ADDR"
              valueFrom:
                configMapKeyRef:
                  name: vault-1
                  key: api-addr
            - name: "VAULT_CLUSTER_ADDR"
              value: "https://vault-1.default.svc.cluster.local:8201"
          args:
            - "server"
            - "-config=/etc/vault/config/vault.hcl"
          ports:
            - name: http
              containerPort: 8200
              protocol: "TCP"
            - name: server
              containerPort: 8201
              protocol: "TCP"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
            - name: vault-tls
              mountPath: /etc/vault/tls
      volumes:
        - name: vault-config
          configMap:
            name: vault
        - name: vault-tls
          secret:
            secretName: vault
