apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: LoadBalancer
  loadBalancerIP: 35.185.225.73
  ports:
    - name: http
      port: 8200
    - name: server
      port: 8201
  selector:
    app: vault
