apiVersion: v1
kind: Service
metadata:
  name: vault-0
spec:
  type: LoadBalancer
  loadBalancerIP: 35.197.93.192
  ports:
    - name: http
      port: 8200
    - name: server
      port: 8201
  selector:
    app: vault
    instance: "0"
