apiVersion: v1
kind: Service
metadata:
  name: vault-1
spec:
  type: LoadBalancer
  loadBalancerIP: 35.197.63.160
  ports:
    - name: http
      port: 8200
    - name: server
      port: 8201
  selector:
    app: vault
    instance: "1"
  publishNotReadyAddresses: true
